# Generated by Django 3.1.1 on 2021-05-30 21:52

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='title_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
